export enum PACK_INIT_NUMBERS {
  DEFAULT_SLIDER_MIN_NUMBER = 0,
  DEFAULT_SLIDER_MAX_NUMBER = 50,
  FIRST_INDEX_FROM_SLIDER_ARRAY = 0,
  SECOND_INDEX_FROM_SLIDER_ARRAY = 1,
  ONE_TIMEOUT_SECOND = 1000,
  CURRENT_PAGE = 1,
}

export enum PAGE_SIZES_OPTIONS {
  FIVE_PACKS_PER_PAGE = 5,
  TEN_PACKS_PER_PAGE = 10,
  TWENTY_FIVE_PACKS_PER_PAGE = 25,
}